services:

  stakeholders-service:
    build:
      context: ./stakeholders-service/StakeholdersService
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - application
    ports:
      - "8081:80"
    environment:
      DATABASE_HOST: stakeholders-db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: super
      DATABASE_NAME: stakeholders
    depends_on:
      - stakeholders-db

  stakeholders-db:
    image: postgres:16
    restart: always
    networks:
      - application
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: super
      POSTGRES_DB: stakeholders
    ports:
      - "5433:5432"
    volumes:
      - stakeholders-db-data:/var/lib/postgresql/data
  
  blog-service:
    build:
      context: ./blog-service
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - application
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      MONGO_URI: mongodb://blog-db:27017/blog
      JWT_SECRET: your_jwt_secret_here
    depends_on:
      - blog-db

  blog-db:
    image: mongo:7
    restart: always
    networks:
      - application
    ports:
      - "27017:27017"
    volumes:
      - blog-db-data:/data/db

  tourism-frontend:
    build:
      context: ./tourism-frontend/tourism-frontend
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - application
    ports:
      - "4200:80"

networks:
  application:
    driver: bridge

volumes:
  stakeholders-db-data:
  blog-db-data: