-- ============================================================
-- V1 — Početna šema tour-service baze
--
-- CREATE TABLE IF NOT EXISTS garantuje idempotentnost:
--   • Postojeća baza  → tabele već postoje, naredbe su no-op,
--     Flyway upisuje V1 u historiju i nastavlja dalje.
--   • Svježa baza     → Flyway kreira tabele od nule.
--
-- Sljedeće promjene šeme idu u V2__..., V3__... itd.
-- NIKAD ne mijenjaj ovaj fajl nakon prvog deploya.
-- ============================================================

CREATE TABLE IF NOT EXISTS tours (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id   BIGINT          NOT NULL,
    created_at  TIMESTAMP       NOT NULL,
    description TEXT,
    difficulty  VARCHAR(255)    NOT NULL,
    name        VARCHAR(255)    NOT NULL,
    price       NUMERIC(38, 2)  NOT NULL,
    status      VARCHAR(255)    NOT NULL
);

CREATE TABLE IF NOT EXISTS tour_tags (
    tour_id BIGINT       NOT NULL REFERENCES tours(id),
    tag     VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS key_points (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tour_id     BIGINT           NOT NULL,
    name        VARCHAR(255)     NOT NULL,
    description TEXT,
    image_url   TEXT,
    latitude    DOUBLE PRECISION NOT NULL,
    longitude   DOUBLE PRECISION NOT NULL
);
