CREATE TABLE IF NOT EXISTS reviews (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tour_id      BIGINT       NOT NULL,
    tourist_id   BIGINT       NOT NULL,
    tourist_name VARCHAR(255),
    rating       INT          NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment      TEXT,
    visit_date   DATE         NOT NULL,
    comment_date TIMESTAMP    NOT NULL
);

CREATE TABLE IF NOT EXISTS review_images (
    review_id BIGINT NOT NULL REFERENCES reviews(id) ON DELETE CASCADE,
    image_url TEXT
);
