ALTER TABLE tours ADD COLUMN IF NOT EXISTS published_at TIMESTAMP;
ALTER TABLE tours ADD COLUMN IF NOT EXISTS archived_at  TIMESTAMP;
ALTER TABLE tours ADD COLUMN IF NOT EXISTS length_in_km DOUBLE PRECISION;

CREATE TABLE IF NOT EXISTS tour_durations (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tour_id             BIGINT       NOT NULL REFERENCES tours(id),
    transport_type      VARCHAR(50)  NOT NULL,
    duration_in_minutes INT          NOT NULL
);
