CREATE TABLE IF NOT EXISTS tour_executions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tourist_id       BIGINT           NOT NULL,
    tour_id          BIGINT           NOT NULL,
    status           VARCHAR(50)      NOT NULL,
    started_at       TIMESTAMP        NOT NULL,
    ended_at         TIMESTAMP,
    last_activity    TIMESTAMP        NOT NULL,
    start_latitude   DOUBLE PRECISION,
    start_longitude  DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS completed_key_points (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id BIGINT    NOT NULL REFERENCES tour_executions(id),
    key_point_id BIGINT    NOT NULL,
    completed_at TIMESTAMP NOT NULL
);
